{application,mavu_snippets,
             [{applications,[kernel,stdlib,elixir,logger,phoenix_html,phoenix,
                             atomic_map,accessible,mavu_utils,mavu_content,
                             memoize,ecto]},
              {description,"MavuSnippets: Text-Snippet - Management for mavu_* projects"},
              {modules,['Elixir.MavuSnippets',
                        'Elixir.MavuSnippets.SnippetCompiler',
                        'Elixir.MavuSnippets.SnippetGroup',
                        'Elixir.MavuSnippets.SnippetGroups']},
              {registered,[]},
              {vsn,"0.1.5"}]}.
